# Generated by Django 5.2.6 on 2025-09-20 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(help_text="Укажите почту", max_length=254, verbose_name="Email")),
                ("country", models.CharField(help_text="Укажите страну", max_length=100, verbose_name="Страна")),
                ("city", models.CharField(help_text="Укажите город", max_length=100, verbose_name="Город")),
                ("street", models.CharField(help_text="Укажите улицу", max_length=100, verbose_name="Улица")),
                (
                    "house_number",
                    models.CharField(help_text="Укажите номер дома", max_length=10, verbose_name="Номер дома"),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Укажите название продукта", max_length=100, verbose_name="Название"),
                ),
                ("model", models.CharField(help_text="Укажите модель", max_length=100, verbose_name="Модель")),
                (
                    "release_date",
                    models.DateField(help_text="Укажите дату выхода на рынок", verbose_name="Дата выхода на рынок"),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "node_type",
                    models.IntegerField(
                        choices=[(0, "Завод"), (1, "Розничная сеть"), (2, "Индивидуальный предприниматель")],
                        help_text="Укажите уровень звена в иерархии сети",
                        verbose_name="Уровень звена",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Укажите задолженность перед поставщиком",
                        max_digits=15,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время создания")),
                (
                    "contact",
                    models.ForeignKey(
                        help_text="Укажите контакты сетевого звена",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics.contact",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="electronics.networknode",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="Укажите продукты", to="electronics.product", verbose_name="Продукты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сетевое звено",
                "verbose_name_plural": "Сетевые звенья",
            },
        ),
    ]
