# Generated by Django 5.2.6 on 2025-09-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(
                blank=True, default="", help_text="Укажите город", max_length=100, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(
                blank=True, default="", help_text="Укажите страну", max_length=100, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="house_number",
            field=models.CharField(
                blank=True, default="", help_text="Укажите номер дома", max_length=10, verbose_name="Номер дома"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="street",
            field=models.CharField(
                blank=True, default="", help_text="Укажите улицу", max_length=100, verbose_name="Улица"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.CharField(
                blank=True, default="", help_text="Укажите модель", max_length=100, verbose_name="Модель"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="release_date",
            field=models.DateField(
                blank=True, help_text="Укажите дату выхода на рынок", null=True, verbose_name="Дата выхода на рынок"
            ),
        ),
    ]
