# Generated by Django 5.2.6 on 2025-09-21 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0002_alter_contact_city_alter_contact_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите задолженность перед поставщиком",
                max_digits=15,
                validators=[
                    django.core.validators.MinValueValidator(0, message="Задолженность не может быть отрицательной.")
                ],
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
    ]
